[project]
name = "cron-monager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.11"
dependencies = [
    "colorama>=0.4.6",
    "paramiko>=4.0.0",
    "pyyaml>=6.0.3",
]
